excludes = [
    ".build/**",
    "blib/**",
    "root/assets/**",
]

[commands.perlimports]
type = "both"
include = [ "**/*.{pl,pm,t,psgi}", "bin/metacpan" ]
cmd = [ "perlimports" ]
lint-flags = ["--lint" ]
tidy-flags = ["-i" ]
ok-exit-codes = 0
expect-stderr = true

[commands.perlcritic]
type = "lint"
include = [ "**/*.{pl,pm,t,psgi}", "bin/metacpan" ]
cmd = [ "perlcritic", "--profile=$PRECIOUS_ROOT/.perlcriticrc" ]
ok-exit-codes = 0
lint-failure-exit-codes = 2

[commands.perltidy]
type = "both"
include = [ "**/*.{pl,pm,t,psgi}", "bin/metacpan" ]
cmd = [ "perltidy", "--profile=$PRECIOUS_ROOT/.perltidyrc" ]
lint-flags = [ "--assert-tidy", "--no-standard-output", "--outfile=/dev/null" ]
tidy-flags = [ "--backup-and-modify-in-place", "--backup-file-extension=/" ]
ok-exit-codes = 0
lint-failure-exit-codes = 2
ignore-stderr = "Begin Error Output Stream"
label = ["perltidy"]

[commands.omegasort-gitignore]
type = "both"
include = "**/.gitignore"
cmd = [ "omegasort", "--sort", "path", "--unique" ]
lint-flags = "--check"
tidy-flags = "--in-place"
ok-exit-codes = 0
lint-failure-exit-codes = 1
ignore-stderr = [
    "The .+ file is not sorted",
    "The .+ file is not unique",
]
