---
# Use the latest 2.1 version of CircleCI pipeline process engine. See:
# https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  codecov: codecov/codecov@4.1.0
# Orchestrate or schedule a set of jobs
workflows:
  docker-compose:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    machine: true
    resource_class: large
    steps:
      - run:
          name: docker compose version
          command: docker compose version
      - checkout
      - run:
          name: create coverage directory
          command: |
            mkdir cover_db
            chmod o+w cover_db
      - run:
          name: docker compose build
          command: |
            docker compose --profile test build api-test
      - run:
          name: run tests with coverage
          command: |
            docker compose --profile test run --env HARNESS_PERL_SWITCHES=-MDevel::Cover -v ./cover_db:/app/cover_db/ api-test bash -c 'prove -lr -j4 t && cover -report codecovbash'
      # We are relying on environment variables from the host to be available when
      # we publish the report, so we publish from the host rather than trying
      # to propagate env variables to the container.
      - codecov/upload:
          file: cover_db/codecov.json
