name: Enable Auto-Merge For bots
on:
  pull_request_target:
    types: [opened]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.user.login == 'metacpan-automation[bot]'
      || github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Generate Auth Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          pull-request-number: ${{ github.event.pull_request.number }}
